CREATE DATABASE RedeSocialGenerica
GO

USE RedeSocialGenerica;
GO

CREATE TABLE Usuario(
	UserId INT PRIMARY KEY IDENTITY(1,1),
	Username VARCHAR(30) NOT NULL UNIQUE,
	Nome VARCHAR(30) NOT NULL,
	Email VARCHAR(30) NOT NULL UNIQUE,
	Senha VARCHAR(30) NOT NULL,
	Endereco VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Post(
	PostId BIGINT PRIMARY KEY IDENTITY(1,1),
	UserId INT FOREIGN KEY REFERENCES Usuario(UserID),
	Descricao VARCHAR(280),
	Imagem VARCHAR(100)
);