CREATE DATABASE SENAISHOP_EVENTOS
GO

USE SENAISHOP_EVENTOS
GO

-- CRIA플O TABELA CLIENTE
CREATE TABLE CLIENTE (
	idCliente INT PRIMARY KEY IDENTITY,
	CPF CHAR(11),
	nomeCliente VARCHAR(25)
);
GO

-- CRIA플O TABELA CATEGORIA
CREATE TABLE CATEGORIA (
	idCategoria TINYINT PRIMARY KEY IDENTITY,
	nomeCategoria VARCHAR(40)
);
GO

-- CRIA플O TABELA SUBCATEGORIA
CREATE TABLE SUBCATEGORIA (
	idSubCategoria TINYINT PRIMARY KEY IDENTITY,
	idCategoria TINYINT FOREIGN KEY REFERENCES CATEGORIA(idCategoria)
);

ALTER TABLE SUBCATEGORIA
ADD nomeSubCategoria VARCHAR(40)
GO

-- CRIA플O TABELA PRODUTO
CREATE TABLE PRODUTO (
	idProduto INT PRIMARY KEY IDENTITY,
	idSubCategoria TINYINT FOREIGN KEY REFERENCES SUBCATEGORIA(idSubCategoria),
	nomeProduto VARCHAR(100),
	preco INT
);
GO

-- CRIA플O TABELA PEDIDO
CREATE TABLE PEDIDO (
	idPedido INT PRIMARY KEY IDENTITY,
	idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente)
);
GO

-- CRIA플O TABELA CARRINHO
CREATE TABLE CARRINHO (
	idCarrinho INT PRIMARY KEY IDENTITY,
	idPedido INT FOREIGN KEY REFERENCES PEDIDO(idPedido),
	idProduto INT FOREIGN KEY REFERENCES PRODUTO(idProduto)
);
GO

